# Generated by Django 4.1.13 on 2024-06-09 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='설문조사 제목')),
                ('description', models.TextField(verbose_name='설문조사 설명')),
                ('thumbnail_path', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='썸네일 이미지 경로')),
                ('is_searchable', models.BooleanField(default=False, verbose_name='검색 가능 여부')),
                ('end_date', models.DateTimeField(verbose_name='설문조사 마감 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 수정 날짜')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '설문조사',
                'verbose_name_plural': '설문조사',
            },
        ),
    ]
