# Generated by Django 4.1.13 on 2024-06-19 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='설문조사 제목')),
                ('description', models.TextField(verbose_name='설문조사 설명')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/', verbose_name='썸네일 이미지 경로')),
                ('is_searchable', models.BooleanField(default=False, verbose_name='검색 가능 여부')),
                ('end_date', models.DateTimeField(verbose_name='설문조사 마감 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 수정 날짜')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '설문조사',
                'verbose_name_plural': '설문조사',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', djongo.models.fields.JSONField(default=dict, verbose_name='응답')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 수정 날짜')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='app.survey', verbose_name='설문조사')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='응답자')),
            ],
            options={
                'verbose_name': '응답',
                'verbose_name_plural': '응답',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='문항 제목')),
                ('question_type', models.CharField(choices=[('SUBJECTIVE', '주관식'), ('SINGLE_CHOICE', '단일 선택')], max_length=15, verbose_name='문항 타입')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='선택지 (객관식)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 수정 날짜')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.survey', verbose_name='설문조사')),
            ],
            options={
                'verbose_name': '설문 문항',
                'verbose_name_plural': '설문 문항',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 수정 날짜')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.survey', verbose_name='설문조사')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
