# Generated by Django 4.1.13 on 2024-06-13 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='문항 제목')),
                ('question_type', models.CharField(choices=[('SUBJECTIVE', '주관식'), ('SINGLE_CHOICE', '단일 선택')], max_length=15, verbose_name='문항 타입')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='선택지 (다중 선택일 경우)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 수정 날짜')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.survey', verbose_name='설문조사')),
            ],
            options={
                'verbose_name': '설문 문항',
                'verbose_name_plural': '설문 문항들',
            },
        ),
    ]
